
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BOI
 */
public class SearchInterface extends javax.swing.JFrame {
    ArrayList<Watt> wattlist;
    String header[] = new String[]{"Name", "Watt", "Time","Time","Date","unit"};
    DefaultTableModel dtm;
    int row,col;
    static double sumUnit=0;
    
    public SearchInterface() {
        initComponents();
        wattlist = new ArrayList<>();
        dtm = new DefaultTableModel(header,0);
        jTable1.setModel(dtm);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jLabel2 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search");
        setResizable(false);

        jTextField1.setVisible(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Watt", "Time", "Time", "Date", "Unite"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField3.setText("0.0");
        jTextField3.setActionCommand("<Not Set>");
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total unite");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Name", "Day", "Month" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMonthChooser1.setVisible(false);

        jLabel2.setVisible(false);
        jLabel2.setText("17000");

        jYearChooser1.setVisible(false);

        jDateChooser1.setVisible(false);
        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jTextField4.setText("0.0");
        jTextField4.setActionCommand("<Not Set>");
        jTextField4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cost (Bath)");

        jTextField5.setText("93.43");
        jTextField5.setActionCommand("<Not Set>");
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Ft (Satang/Unit)");

        jButton3.setText("Bar Chart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMonthChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        
           
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        wattlist.clear();
        sumUnit=0;
        jTextField3.setText((String.format("%.2f",sumUnit)));
        sumUnit=0;
        String input = jTextField1.getText();
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String date = "";
        int month = 0;
        int year = 0;
        String data;
        
        try {
            Reader reader = new FileReader("Wattlist.txt");
            BufferedReader bf = new BufferedReader(reader);
            int Select = 0; 
            if(jComboBox1.getSelectedItem().toString()=="Name"){
                Select = 0;
            }
            else if (jComboBox1.getSelectedItem().toString()=="Day"){
                Select = 4;
                date = sdf.format(jDateChooser1.getDate());
            }
            else if (jComboBox1.getSelectedItem().toString()=="Month"){
                Select = 5;
                month = jMonthChooser1.getMonth()+1;
                year = jYearChooser1.getYear();
            }
            //System.out.println(Select);
            while((data = bf.readLine())!=null){
                String[] sp = data.split(",");
                String[] s5 = sp[4].split("-");
                //System.out.println(s5[0]+ " " +s5[1]+" "+s5[2]+" > "+month + " - "+ year);
                if(input.equals(sp[Select])||date.equals(sp[Select])||(month==Integer.parseInt(s5[1])&&year==Integer.parseInt(s5[2]))){
                    wattlist.add(new Watt(sp[0],Integer.parseInt(sp[1]),sp[2],sp[3],sp[4],Double.parseDouble(sp[5])));
                    Object[] objs = {sp[0],Integer.parseInt(sp[1]),sp[2],sp[3],sp[4],Double.parseDouble(sp[5])};
                    dtm.addRow(objs);
                    //System.out.println(sp[0]+","+sp[1]+","+sp[2]+","+sp[3]+","+sp[4]+","+sp[5]);
                    sumUnit += Double.parseDouble(sp[5]);
                }
            } 
            jTextField3.setText((String.format("%.2f",sumUnit)));
            //////Cost
            double cost = 0.0, tod = 0.0 , unitt = 0.0;
            ////////1
            unitt=sumUnit;
                if(sumUnit>400)
                {
                    tod=0;
                    tod = sumUnit - 400;
                    cost += tod * 4.4217;
                    sumUnit = sumUnit - tod;
                }
                if(sumUnit>150&&sumUnit<=400)
                {
                    tod=0;
                    tod = sumUnit - 150;
                    cost += tod * 4.2218;
                    sumUnit = sumUnit - tod;
                    System.out.println(cost+"1 "+tod);
                }
                if(sumUnit>100&&sumUnit<=150)
                {
                    tod=0;
                    tod = sumUnit - 100;
                    cost += tod * 3.7171;
                    sumUnit = sumUnit - tod;
                    System.out.println(cost+" "+tod);
                }
                if(sumUnit>35&&sumUnit<=100)
                {
                    tod=0;
                    tod = sumUnit - 35;
                    cost += tod * 3.6237;
                    sumUnit = sumUnit - tod;
                    System.out.println(cost+" "+tod);
                }
                if(sumUnit>25&&sumUnit<=35)
                {
                    tod=0;
                    tod = sumUnit - 25;
                    cost += tod * 3.2405;
                    sumUnit = sumUnit - tod;
                   System.out.println(cost+" "+tod);
                }
                if(sumUnit>15&&sumUnit<=25)
                {
                    tod=0;
                    tod = sumUnit - 15;
                    cost += tod * 2.9882;
                    sumUnit = sumUnit - tod;
                    System.out.println(cost+" "+tod);
                }
                if(sumUnit>0&&sumUnit<=15)//100
                {
                    tod=0;
                    tod = sumUnit;
                    cost += tod * 2.3488;
                    sumUnit = sumUnit - tod;
                    System.out.println(cost+" "+sumUnit);
                }
                //System.out.println(" ");
                //System.out.println(cost);
                if(cost != 0){
                    cost += 8.19;
                
                //System.out.println(cost);
            ////////2
            cost += unitt*(93.43/100);
            System.out.println(cost);
            ////////3
            cost += cost*0.07;
            }
            jTextField4.setText((String.format("%.2f",cost)));
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SearchInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SearchInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        wattlist.clear();
        sumUnit=0;
        jTextField3.setText("0.0");
        jTextField4.setText("0.0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained

    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString()=="Name"){
            jLabel2.setVisible(true);
            jTextField1.setVisible(true);
            jLabel2.setVisible(false);
            
            jDateChooser1.setVisible(false);
            jMonthChooser1.setVisible(false);
            jYearChooser1.setVisible(false);
        }
        else if(jComboBox1.getSelectedItem().toString()=="Day")
        {
            jDateChooser1.setVisible(true);
            
            jMonthChooser1.setVisible(false);
            jYearChooser1.setVisible(false);
            jTextField1.setVisible(false);
        }
        else if(jComboBox1.getSelectedItem().toString()=="Month")
        {
            jMonthChooser1.setVisible(true);
            jYearChooser1.setVisible(true);
            
            jDateChooser1.setVisible(false);
            jTextField1.setVisible(false);
        }
        else
        {
            jDateChooser1.setVisible(false);
            jMonthChooser1.setVisible(false);
            jYearChooser1.setVisible(false);
            jTextField1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int year = jYearChooser2.getYear();
        Reader reader;
        double Jan = 0,Feb = 0,Mar = 0,Apr = 0,May = 0,Jun = 0,Jul = 0,Aug = 0,Sept = 0,Oct = 0,Nov = 0,Dec = 0;
        try {
            reader = new FileReader("Wattlist.txt");
            BufferedReader bf = new BufferedReader(reader);
            String data;
            while((data = bf.readLine())!=null){
                    String[] sp = data.split(",");
                    String[] s5 = sp[4].split("-");
                    if(year==Integer.parseInt(s5[2])){
                       if("01".equals(s5[1])){
                           Jan += Double.parseDouble(sp[5]);
                           //System.out.println("01");
                       }
                       else if("02".equals(s5[1])){
                           Feb += Double.parseDouble(sp[5]);
                           //System.out.println("02");
                       }
                       else if("03".equals(s5[1])){
                           Mar += Double.parseDouble(sp[5]);
                           //System.out.println("03");
                       }
                       else if("04".equals(s5[1])){
                           Apr += Double.parseDouble(sp[5]);
                           //System.out.println("04");
                       }
                       else if("05".equals(s5[1])){
                           May += Double.parseDouble(sp[5]);
                           //System.out.println("05");
                       }
                       else if("06".equals(s5[1])){
                           Jun += Double.parseDouble(sp[5]);
                           //System.out.println("06");
                       }
                       else if("07".equals(s5[1])){
                           Jul += Double.parseDouble(sp[5]);
                           //System.out.println("07");
                       }
                       else if("08".equals(s5[1])){
                           Aug += Double.parseDouble(sp[5]);
                           //System.out.println("08");
                       }
                       else if("09".equals(s5[1])){
                           Sept += Double.parseDouble(sp[5]);
                           //System.out.println("09");
                       }
                       else if("10".equals(s5[1])){
                           Oct += Double.parseDouble(sp[5]);
                           //System.out.println("10");
                       }
                       else if("11".equals(s5[1])){
                           Nov += Double.parseDouble(sp[5]);
                           //System.out.println("11");
                       }
                       else if("12".equals(s5[1])){
                           Dec += Double.parseDouble(sp[5]);
                           //System.out.println("12");
                       } 
                    }
                } 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SearchInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SearchInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(Jan, "Unit", "Jan");
        dataset.setValue(Feb, "Unit", "Feb");
        dataset.setValue(Mar, "Unit", "Mar");
        dataset.setValue(Apr, "Unit", "Apr");
        dataset.setValue(May, "Unit", "May");
        dataset.setValue(Jun, "Unit", "Jun");
        dataset.setValue(Jul, "Unit", "Jul");
        dataset.setValue(Aug, "Unit", "Aug");
        dataset.setValue(Sept, "Unit", "Sept");
        dataset.setValue(Oct, "Unit", "Oct");
        dataset.setValue(Nov, "Unit", "Nov");
        dataset.setValue(Dec, "Unit", "Dec");
        JFreeChart chart = ChartFactory.createBarChart("Bar chart of "+year,"Month", "Unit", dataset, PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLACK);
        ChartFrame frame = new ChartFrame("Bar Chart",chart);
        frame.setVisible(true);
        frame.setSize(650,550);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    // End of variables declaration//GEN-END:variables
}
